openfaas/openfaas-operator

.travis.yml, Dockerfile, Dockerfile.armhf, artifacts/figlet-armhf.yaml, artifacts/gofast.yaml, artifacts/nodeinfo.yaml, artifacts/o6s-amd64.yaml, artifacts/o6s-rbac.yaml, main.go, pkg/controller/secrets.go
This PR adds the following:
* Split RBAC into a cluster role for functions & events and a role for openfaas-fn namespace fix #11 
* Run the controller as non root fix #10
* Fix image pull secret for Kubernetes 1.9 see https://github.com/openfaas/faas-netes/pull/177
* Fix Docker Registry push see https://github.com/openfaas/faas/issues/650
All changes were tested on GKE with `stefanprodan/faas-o6s:0.6.0`.
=> Security improvements 

pkg/controller/secrets.go, pkg/controller/secrets_test.go
**What**
- Filter the existing volumes to remove pre-existing secrets volumes
- If the secrets volume is still needed, re-append it
- Add unit tests
**Why**
- This ensure that we do not incorrectly add the volume multiple times
- This ensures that the secrets volume is removed if the secrets are
removed from the function
**Note**
This implements the same changes as openfaas/faas-netes#192
=> Ensure that secret volumes are added exactly once

pkg/controller/secrets.go, pkg/controller/secrets_test.go
**What**
- create `secretsMountPath` constant
- update the volume mount to set the mount path to the `secretsMountPath`
**Why**
- this will ensure that the secrets required for the function business
logic do not interfer with standard locations that other systems may
want to modify.
**Notes**
Implement openfaas/faas#692
Signed-off-by: Lucas Roesler <roesler.lucas@gmail.com>
=> Move secrets mount path to /var/openfaas/secrets

README.md, artifacts/operator-amd64.yaml, artifacts/operator-armhf.yaml, pkg/controller/controller.go, pkg/controller/deployment.go
This PR does the following:
* fix ClusterIP creation race condition when multiple operator instances are running
* improve logging (deployment update errors, service creation errors)
* set deployment strategy to max unavailable 0 (ensure no downtime during a rolling update)
* update the gateway and operator versions in the deploy manifests
* update readme to reflect the secrets path change
All changes have been tested on GKE 1.10
=>  Fix ClusterIP creation race condition and other improvements

artifacts/operator-amd64.yaml, artifacts/operator-armhf.yaml, artifacts/operator-rbac.yaml, pkg/controller/controller.go, pkg/controller/deployment.go, pkg/controller/resources.go, pkg/controller/secrets.go, pkg/controller/secrets_test.go, pkg/controller/service.go
This PR does the following:
- rename CRD group to openfaas.com in RBAC
- rename imports from `faasv1alpha1` to `faasv1`
- rename the Kubernetes event owner from `faas-k8s` to `openfaas-operator`
- bump image version to `openfaas-operator:0.7.1`
- CRUD operations were tested with kubectl and Gateway UI
- tested on GKE 1.10 with stefanprodan/openfaas-operator:0.7.1
=> Rename CRD group to openfaas.com Part2

.travis.yml, Makefile, README.md
This PR does the following:
- publish the Docker image to `openfaas` repository on Docker Hub and Quay.io
- update the readme with the official Helm install instructions 
Ref https://github.com/openfaas/faas/issues/741
Fix #28
=> Push image to openfaas repo on Quay.io and Docker Hub

README.md, artifacts/operator-rbac.yaml, main.go
- restrict the kubernetes informers to the functions namespace
- remove the cluster role from RBAC
- mention in the readme the minimum supported Kubernetes version
- tested on GKE 1.10 with the new RBAC
- fix #29
Signed-off-by: Stefan Prodan <stefan.prodan@gmail.com>
=> Make the operator work with Role instead of Cluster Role

artifacts/operator-crd.yaml
This PR does the following:
- make `spec.name` and `spec.image` mandatory 
- validate function name as Kubernetes deployment name
- validate limits and requests fix #37 
- validate secrets and constraints as string array
- prep for multi-version support
- add fn as short name
- tested on GKE 1.10 with kubectl 1.11
Fix #12
Signed-off-by: Stefan Prodan <stefan.prodan@gmail.com>
=> Add openAPIV3Schema validation to CRD

pkg/server/list.go, pkg/server/replicas.go
This PR fixes #41 
- log warning if replica count query fails
- do not return HTTP 500 if a function deployment is not ready
- return 0 replicas if a function deployment is not found
- tested on GKE 1.10 with an unknown image pull secret
=> Handle replica count query failures

Gopkg.lock, Gopkg.toml, artifacts/env.yaml, pkg/controller/annotations_test.go, pkg/controller/controller.go, pkg/controller/deployment.go, pkg/server/server.go, vendor/github.com/google/go-cmp/LICENSE, vendor/github.com/google/go-cmp/cmp/compare.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go, vendor/github.com/google/go-cmp/cmp/internal/function/func.go, vendor/github.com/google/go-cmp/cmp/internal/value/format.go, vendor/github.com/google/go-cmp/cmp/internal/value/sort.go, vendor/github.com/google/go-cmp/cmp/options.go, vendor/github.com/google/go-cmp/cmp/path.go, vendor/github.com/google/go-cmp/cmp/reporter.go, vendor/github.com/google/go-cmp/cmp/unsafe_panic.go, vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go
- use go-cmp to reliably detect changes in function spec
- log function spec diff before update
- fix deployment annotation append bug by copying the values from function spec
- set the default API namespace the same as the controller default
- change K8s event logger verbosity level to prevent log filling up when a function goes into crash loop, when debugging the event log can be enabled using the -v=3 flag
Fix  #50
Tested with `stefanprodan/openfaas-operator:fix50v2` on GKE 1.10 by applying changes to every function spec field.
Function definition:
```yaml
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
name: env
spec:
name: env
image: stefanprodan/of-env
annotations:
test.min: "1"
test.max: "2"
labels:
com.openfaas.scale.min: "2"
com.openfaas.scale.max: "5"
environment: …
```
=>  Refactor function spec change detection

pkg/apis/openfaas/v1alpha2/types.go
Added omitempty to FunctionResources (Memory and CPU)
Fixes: https://github.com/openfaas-incubator/openfaas-operator/issues/54
Signed-off-by: Bart Smykla <bsmykla@vmware.com>
- I deployed a function without limits
- I deployed a function with only CPU limit
- I deployed a function with only memory limit
- I deployed a function with both CPU and memory limits
Results:
```
=== RUN   Test_Access_Secret
=== RUN   Test_Access_Secret/Empty_QueryString
--- PASS: Test_Access_Secret (27.81s)
--- PASS: Test_Access_Secret/Empty_QueryString (27.51s)
verify.go:71: [1/30] Got correct response: 200 - https://gateway/function/test-secret
=== RUN   Test_Deploy_Stronghash
--- PASS: Test_Deploy_Stronghash (0.39s)
=== RUN   Test_Deploy_PassingCustomEnvVars_AndQueryString
=== RUN …
```
=> Fixed validation of resources

Dockerfile, Dockerfile.armhf
- Bump the golang docker base image to the 1.10 tag, this is currently
golang 1.10.5
- Bumpe alpine docker base image to 3.8
Resolves #57 
I tried running the certifier, but got a nil pointer error
```go
=== RUN   Test_Access_Secret
=== RUN   Test_Access_Secret/Empty_QueryString
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x124e679]
goroutine 9 [running]:
testing.tRunner.func1(0xc42011a1e0)
/usr/local/Cellar/go/1.10.2/libexec/src/testing/testing.go:742 +0x29d
panic(0x1297d40, 0x146e1e0)
/usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
github.com/openfaas/certifier/tests.invokeWithVerb(0xc42011a1e0, …
```
=> Bundle golang to 1.10 and alpine to 3.8

main.go, pkg/server/apply.go, pkg/server/delete.go, pkg/server/health.go, pkg/server/info.go, pkg/server/list.go, pkg/server/replicas.go, pkg/server/server.go
Fix rate limiting latency for list endpoint as shown in #64 
Signed-off-by: Alex Ellis (VMware) <alexellis2@gmail.com>
- the list endpoint of the REST API was making too many API calls
in a short period of time (1 per existing function in cluster)
so we hit rate limiting and the Kubernetes API server started to
rate limit us causing a huge delay to the end-user and timeouts.
This issue was found when @bartsmykla tried out OpenFaas Cloud with
the Operator which makes use of the REST API. The UI would have
had the same issue causing a poor and confusing experience for
our users.
I logged the issue and explored a fix in #64 
An initial fix would have used List instead of Get to reduce API
calls, but this fix follows an idea from @stefanprodan to make use of
a shared Informer which already …
=> Fix rate limiting latency for list endpoint

pkg/controller/controller.go
Add informer for Service definitions
Signed-off-by: Alex Ellis (VMware) <alexellis2@gmail.com>
- adds informer for Service definitions to fix #61 and #60 -
since it seemed that deleting Service definitions was not tracked
or synchronized and the code was depending on the Deployment
from being deleted or updated.
Fixes #61 and #60
Tested on K8s 1.10 on single node Linux cluster by deleting
Service and seeing it re-created in the logs. Happy path of
deploying from store also works unaffected.
Improved durability when resources owned by controller are deleted manually or accidentally by automation.
=> Add informer for Service definitions

pkg/server/apply.go, pkg/server/delete.go, pkg/server/info.go, pkg/server/list.go, pkg/server/replicas.go
Added error message to the reponse packet
Signed-off-by: pcsx22 <sushil.paneru1@gmail.com>
This PR resolves #71
=> Return error messages from HTTP handlers in body

pkg/controller/controller.go
Signed-off-by: Wouter Horré <wouter@zenjoy.be>
Copy the `imagePullPolicy` passed as an argument to `NewController` into the controller structure.
The `imagePullPolicy` passed as an argument to `NewController` was not put into the controller structure. The pull request fixes this issue.
Fixes #56 
I have successfully verified that this change fixes #56 by deploying this to our cluster and verifying the `imagePullPolicy` on a newly created function.
=> Put imagePullPolicy into the controller structure

README.md, pkg/controller/deployment.go
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
The com.openfaas.serviceaccount annotation is used from the
function spec to assign a serviceAccount to the podSpec.
Completes https://github.com/openfaas/faas-netes/issues/409 for the Operator, but needs adding to faas-netes next.
Tested on Kind with Kubernetes 1.13. First by setting the value
as build-robot (as per README.md) and seeing it applied on the
podSpec, then by removing the annotation and seeing it go back
to "default".
No impact to existing users, to adopt users can now set the annotation on the function CRD spec.
=> Populate serviceAccount based upon annotation

Gopkg.lock, Gopkg.toml, main.go, pkg/controller/controller.go, pkg/controller/deployment.go, pkg/controller/probes.go, pkg/controller/probes_test.go, vendor/github.com/openfaas/faas-netes/LICENSE, vendor/github.com/openfaas/faas-netes/types/read_config.go, vendor/github.com/openfaas/faas-netes/types/requests.go
Port http/exec probes from faas-netes https://github.com/openfaas/faas-netes/pull/414
- add faas-netes types package dep
- load the bootstrap config from env vars
- create probes based on http_probe var
- add tests for exec and http probes
Fix: #78 
Tested on GKE with `http_probe` env var false/true
=>  Add support for HTTP probes

Gopkg.lock, Gopkg.toml, pkg/server/server.go, vendor/github.com/openfaas/faas-provider/.gitignore, vendor/github.com/openfaas/faas-provider/README.md, vendor/github.com/openfaas/faas-provider/serve.go, vendor/github.com/openfaas/faas-provider/types/config.go
Vendoring the faas-provider package version 0.9.0
and renamig the Health to HealthHandler
Signed-off-by: Martin Dekov <mdekov@vmware.com>
Renaming `Health` to `HealthHandler` in `server.go` and re-vendor the faas-provicer package 0.9.0
Closes https://github.com/openfaas/faas-provider/issues/17
Built image:
Create instance with the operator turned on using helm:
```
helm upgrade openfaas --install openfaas/openfaas     --namespace openfaas      --set functionNamespace=openfaas-fn     --set operator.create=true --setoperator.image=martindekov/operator_image:0.0.1
```
curl `healthz` endpoint:
```
$ curl http://192.168.99.100:31112/healthz -i
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Sat, 04 May 2019 10:24:01 GMT
```
N/A
=> Vendor faas-provier 0.9.0

pkg/controller/controller.go, pkg/server/apply.go
Remove comparison between the `.spec` fields so that resources can be re-synced. The diff constraint is no longer needed since we use an annotation to prevent the mounts from being overwritten.
Do not re-apply `resourceVersion` on function update to allow resources to be re-synced.
Fix: #95
Fix: #89
Tested on EKS 1.14 by applying the nodeinfo function with and without changes.
No impact to current users.
=> Remove sync constraints

pkg/apis/openfaas/v1/types.go, pkg/controller/annotations_test.go
Mark optional CRD fields to fix json deserialisation errors like:
```
Invalid value: "null": spec.constraints in body must be of type array: "null"
```
None
=> Mark optional CRD fields
